name: offline_articles_app
description: A Flutter app with offline capabilities using Hive and GetX, showcasing MVVM architecture.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  get: ^4.6.6
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  connectivity_plus: ^6.1.2
  cached_network_image: ^3.2.3
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.3.3
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Add assets if needed in your project
  # assets:
  #   - assets/

  # To add custom fonts, uncomment the following lines and add your fonts:
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: fonts/CustomFont-Regular.ttf
  #       - asset: fonts/CustomFont-Bold.ttf
